# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               다정한 개발자
tagline:            '내 머릿속의 지우개...'
#description:         This site is Jake Lim's Blog
#url:                 https://gamejigi.github.io
#baseurl:             https://gamejigi.github.io
paginate:            8

# About/contact
author:
  name:              Jake Lim
  url:               https://twitter.com/gemji
  email:             gamejigi@gmail.com

# Custom vars
version:             1.0.0


gems: [jekyll-paginate]
